Metrics/AbcSize:
  Max: 38

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 74

#Metrics/CyclomaticComplexity:
#  Max: 8

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 27
