# Offense count: 10
#Metrics/AbcSize:
#  Max: 38

# Offense count: 4
# Configuration parameters: CountComments, ExcludedMethods.
#Metrics/BlockLength:
#  Max: 74

# Offense count: 2
#Metrics/CyclomaticComplexity:
#  Max: 8

# Offense count: 8
# Configuration parameters: CountComments.
#Metrics/MethodLength:
#  Max: 27
